### ISSUE TITLE
time stamp of velodyne packets does not changed

### ISSUE THREAD

**Issue by m-seiya** [autowarefoundation/autoware_ai#448]
# Problem
## Expected Behavior
```
rostopic echo /velodyne_packets/header
seq: 0
stamp: 
  secs: 1543996478
  nsecs: 959228516      <--------nsec 
frame_id: velodyne
---
seq: 1
stamp: 
  secs: 1543996479
  nsecs:  60075283   <----------nsec  is changed,usually.
frame_id: velodyne
---
```

## Actual Behavior
```
rostopic echo /velodyne_packets/header
seq: 4699
stamp: 
  secs: 904636608      
  nsecs:     32663       <--------nsec 
frame_id: "velodyne"
---
seq: 4700
stamp: 
  secs: 904636608    <----------sec  is not changed and  it should be about 1543996479.
  nsecs:     32663      <----------nsec is not changed .
frame_id: "velodyne"
---
```
## Steps to Reproduce the Problem

  1.connect VelodyneVLP-16
  2. start Runtime manager and select sencing tab and  click  Velodyne VLP-16
  3. check  time stamp of /velodyne_packets.

it also happened Velodyne32C
It always occurs on a specific PC.

## Specifications

  - Ubuntu version:16.04
  - ROS version:kinetic
  - Autoware branch:master 1.9.1 Autoware branch:master 1.6.1
